SplineFontDB: 3.2
FontName: Untitled1
FullName: Untitled1
FamilyName: Untitled1
Weight: Regular
Copyright: Copyright (c) 2026, Dev
UComments: "2026-7-29: Created with FontForge (http://fontforge.org)"
Version: 001.000
DefaultBaseFilename: SysA
ItalicAngle: 0
UnderlinePosition: -1
UnderlineWidth: 0
Ascent: 13
Descent: 3
InvalidEm: 0
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
XUID: [1021 824 -2048086036 18521]
FSType: 0
OS2Version: 0
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1785309157
ModificationTime: 1785402802
PfmFamily: 17
TTFWeight: 400
TTFWidth: 5
LineGap: 1
VLineGap: 0
OS2TypoAscent: 0
OS2TypoAOffset: 1
OS2TypoDescent: 0
OS2TypoDOffset: 1
OS2TypoLinegap: 1
OS2WinAscent: 0
OS2WinAOffset: 1
OS2WinDescent: 0
OS2WinDOffset: 1
HheadAscent: 0
HheadAOffset: 1
HheadDescent: 0
HheadDOffset: 1
OS2Vendor: 'PfEd'
MarkAttachClasses: 1
DEI: 91125
Encoding: UnicodeFull
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -48
AntiAlias: 1
FitToEm: 0
WinInfo: 875 35 12
BeginPrivate: 0
EndPrivate
Grid
-16 2 m 0
 32 2 l 1024
13 21 m 0
 13 -11 l 1024
12 21 m 0
 12 -11 l 1024
10 21 m 0
 10 -11 l 1024
11 21 m 0
 11 -11 l 1024
9 21 m 0
 9 -11 l 1024
8 21 m 0
 8 -11 l 1024
7 21 m 0
 7 -11 l 1024
6 21 m 0
 6 -11 l 1024
5 21 m 0
 5 -11 l 1024
4 21 m 0
 4 -11 l 1024
3 21 m 0
 3 -11 l 1024
2 21 m 0
 2 -11 l 1024
1 21 m 0
 1 -11 l 1024
-16 -2 m 0
 32 -2 l 1024
-16 -1 m 0
 32 -1 l 1024
-16 1 m 0
 32 1 l 1024
-16 4 m 0
 32 4 l 1024
-16 3 m 0
 32 3 l 1024
-16 5 m 0
 32 5 l 1024
-16 6 m 0
 32 6 l 1024
-16 7 m 0
 32 7 l 1024
-16 8 m 0
 32 8 l 1024
-16 9 m 0
 32 9 l 1024
-16 10 m 0
 32 10 l 1024
-16 11 m 0
 32 11 l 1024
-15 12 m 0
 33 12 l 1024
EndSplineSet
EndSplineFont
